# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18l5dMveswBv2B5Gybse-WC7vQ8-5kBqy

# Python Mini Project: Library Management System

This project implements a simple Library Management System using Object-Oriented Programming (OOP) principles in Python. It allows users to manage books, including adding new books, listing available books, borrowing books, and returning them. The system also features data persistence using file handling (CSV) and robust error handling for user inputs.
"""

import pandas as pd
import os

class Book:
    """Represents a book in the library."""
    def __init__(self, title, author, isbn, available=True):
        self.title = title
        self.author = author
        self.isbn = isbn
        self.available = available

    def __str__(self):
        status = "Available" if self.available else "Borrowed"
        return f"Title: {self.title}, Author: {self.author}, ISBN: {self.isbn}, Status: {status}"

    def to_dict(self):
        return {
            'title': self.title,
            'author': self.author,
            'isbn': self.isbn,
            'available': self.available
        }

class Library:
    """Manages the collection of books and library operations."""
    def __init__(self, filename='library_data.csv'):
        self.filename = filename
        self.books = []
        self._load_books()

    def _load_books(self):
        """Loads book data from the CSV file."""
        if os.path.exists(self.filename):
            try:
                df = pd.read_csv(self.filename)
                for index, row in df.iterrows():
                    self.books.append(Book(row['title'], row['author'], row['isbn'], row['available']))
                print(f"Loaded {len(self.books)} books from {self.filename}")
            except Exception as e:
                print(f"Error loading books from {self.filename}: {e}")
                self.books = [] # Ensure books list is empty on error
        else:
            print(f"No existing data file '{self.filename}' found. Starting with an empty library.")

    def _save_books(self):
        """Saves current book data to the CSV file."""
        if not self.books:
            # If there are no books, create an empty DataFrame to save headers
            df = pd.DataFrame(columns=['title', 'author', 'isbn', 'available'])
        else:
            data = [book.to_dict() for book in self.books]
            df = pd.DataFrame(data)
        try:
            df.to_csv(self.filename, index=False)
            print(f"Saved {len(self.books)} books to {self.filename}")
        except Exception as e:
            print(f"Error saving books to {self.filename}: {e}")

    def add_book(self, title, author, isbn):
        """Adds a new book to the library."""
        if not all([title, author, isbn]):
            print("Error: All fields (title, author, ISBN) must be provided.")
            return
        if any(book.isbn == isbn for book in self.books):
            print(f"Error: A book with ISBN {isbn} already exists.")
            return
        book = Book(title, author, isbn)
        self.books.append(book)
        self._save_books()
        print(f"Book '{title}' added successfully.")

    def list_books(self, show_all=True):
        """Lists books in the library. Can show all or only available books."""
        if not self.books:
            print("The library is currently empty.")
            return
        print("\n--- Current Library Books ---")
        found_books = False
        for book in self.books:
            if show_all or book.available:
                print(book)
                found_books = True
        if not found_books:
            if show_all:
                print("No books found in the library.")
            else:
                print("No available books found in the library.")
        print("---------------------------")

    def borrow_book(self, isbn):
        """Marks a book as borrowed."""
        for book in self.books:
            if book.isbn == isbn:
                if book.available:
                    book.available = False
                    self._save_books()
                    print(f"Book '{book.title}' (ISBN: {isbn}) has been borrowed.")
                    return True
                else:
                    print(f"Book '{book.title}' (ISBN: {isbn}) is already borrowed.")
                    return False
        print(f"Error: Book with ISBN {isbn} not found.")
        return False

    def return_book(self, isbn):
        """Marks a book as available."""
        for book in self.books:
            if book.isbn == isbn:
                if not book.available:
                    book.available = True
                    self._save_books()
                    print(f"Book '{book.title}' (ISBN: {isbn}) has been returned.")
                    return True
                else:
                    print(f"Book '{book.title}' (ISBN: {isbn}) is already available.")
                    return False
        print(f"Error: Book with ISBN {isbn} not found.")
        return False